title: ingenuity.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6899642
  brandStrength: 0.6090463204309344
  lightness: 0.3422939
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.3261649
typography_spectrum: 0.4408602
description: something beyond drones...
navigation:
  - name: inav history
    id: c04c24f8-89d5-4547-97ff-70d1780acaea
    type: content
layout_spectrum: 1
name: Admirabilis
